### ISSUE TITLE
Event Notification

### ISSUE THREAD

**Issue by Jbrouwers2** [maximecharriere/iai-gxipy#1]
Hi,

First of all thank you for creating the Python API for Daheng Imaging cameras. 

The[ Mercury2 GigE Cameras User Manual ](https://machinevision.co.th/wp-content/uploads/2020/08/MERCURY2-GigE-Cameras-User-Manual_V1.0.2_compressed.pdf) describes in Section 8.6 the possibility of the camera to generate and transmit events. I was wondering whether I can enable the event notification of the camera using this API?

Thank you in advance!

**Comment by maximecharriere** [comment]
Hello,
This is only a repo to publish the official Daheng Imaging API on PyPi in order to be able to install the API via `pip`.  (See on [PyPi](https://pypi.org/project/iai-gxipy/))
I'm not the dev behind this API.  
Look at the [Python Interface Development User Manual.pdf](https://github.com/maximecharriere/iai-gxipy/blob/main/Python%20Interface%20Development%20User%20Manual.pdf) to see if you find how to use events.  
I would be interested to know if you have found anything.

**Comment by Jbrouwers2** [comment]
Hi,

Excuse me, sorry for my mistake! However, thank you for updating me and pointing me to the developing manual. It helped me implementing a callback function on the get image. 

I've reached out to the support of the Daheng and unfortunately it is not yet possible to include camera events such as exposureend. They only support it for C++ or C#.
